<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>

		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>

		<ApplicationIcon>..\assets\app.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationVersion>1.0.0</ApplicationVersion>

		<Platforms>x64</Platforms>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<UseWinUI>true</UseWinUI>

		<DefaultLanguage>en-US</DefaultLanguage>
		<SupportedCultures>en-US</SupportedCultures>

		<SelfContained>true</SelfContained>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<WindowsPackageType>None</WindowsPackageType>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\assets\**\*">
			<Link>Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.*" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
	</ItemGroup>
</Project>